# Generated by Django 5.2.13 on 2026-04-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='view_count',
        ),
    ]
